# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  panda1_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  panda1_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  panda2_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0